# __________________________________________________
#
# COMMANDS CONFIGURATION, SEE BELOW FOR FURTHER INFORMATION
# 
# <command name>:
#   description: <the description of the command> (string)
#   test: <whether the command should be shown or not> (false/true)
#   options: <the options needed for this command> (array of command_option)
#
#   <command_option>:
#     id: <the id of the option>
#     name: <the name of the option wich will be displayed bold on the left> (string)
#     description <the description of the option wich will be displayed on the right> (right)
#     required: <whether it's mandatory to input the option before sending> (true/false)
#     type: <what type of data can be inputted in this option> (application_command_option_type)
#
#     <application_command_option_type>:
#       Subcommand: 1
#       SubcommandGroup: 2
#       String: 3
#       Integer: 4
#       Boolean: 5
#       User: 6
#       Channel: 7
#       Role: 8
#       Mentionable: 9
#       Number: 10
#       Attachment: 11
# 
# __________________________________________________


# VARIABLES

language-choices: &language_choices
  - name: "English"
    value: "en"
  - name: "Italiano"
    value: "it"
  - name: "Español"
    value: "es"


# MESSAGES 

msg-already-setup:
  name: "already-setup"
  description: "Send already-setup message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-category-used:
  name: "category-used"
  description: "Send category-used message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-no-categories:
  name: "no-categories"
  description: "Send no-categories message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-not-admin:
  name: "not-admin"
  description: "Send not-admin message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-not-setup:
  name: "not-setup"
  description: "Send not-setup message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-setup-successful:
  name: "setup-successful"
  description: "Send setup-successful message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-ticket-opened:
  name: "ticket-opened"
  description: "Send ticket-opened message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-unknown-category:
  name: "unknown-category"
  description: "Send unknown-category message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-unknown-command:
  name: "unknown-command"
  description: "Send unknown-command message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-unknown-embed:
  name: "unknown-embed"
  description: "Send unknown-embed message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

msg-unknown-message:
  name: "unknown-message"
  description: "Send unknown-message message"
  test: true
  options:
    - name: "language"
      description: "The message language"
      required: false
      type: 3
      choices: *language_choices

# MISC

ping:
  name: "ping"
  description: "Get bot ping"
  test: false

server-info:
  name: "server"
  description: "Display information on the server"
  test: true

tck-info:
  name: "tck"
  description: "Infomration about the server ticketing system"
  test: false

setup-info:
  name: "setup"
  description: "Display information on how to setup the bot"
  test: true



# SETTINGS

set-transcripts_channel:
  name: "transcripts-channel"
  description: "Set the channel where the ticket transcripts will be sent"
  test: false
  options:
    - name: "channel"
      description: "The channel where the ticket transcripts will be sent. Leave blank to disable the current channel."
      required: false
      type: 7

set-default_cateogry_enable:
  name: "default-category-enable"
  description: "Enable the default category for the server (use one default category)"
  test: false
  
set-default_cateogry_disable:
  name: "default-category-disable"
  description: "Disable the default category for the server (use ticket categories)"
  test: false

set-add_ticket_category:
  name: "add-category"
  description: "Add a ticket category to the server"
  test: false
  options:
    - name: "name"
      description: "The name of the category to be added (it must be unique)"
      required: true
      type: 3

set-admin_role:
  name: "admin"
  description: "Setup the BotAdmin role in the bot database"
  test: false
  options:
    - name: "role"
      description: "The role that can run every bot command, even the most delicate ones (settings commands)"
      required: false
      type: 8

set-default_ticket_emoji:
  name: "default-emoji"
  description: "Set the default emoji for the tickets"
  test: false
  options:
    - name: "emoji"
      description: "The emoji to be used as the default ticket emoji"
      required: true
      type: 3

set-language:
  name: "language"
  description: "Set the language for this server"
  test: false
  options:
    - name: "language"
      description: "The language you want the bot to use"
      required: true
      type: 3
      choices: *language_choices

set-helper_role:
  name: "helper"
  description: "Setup the helper role in the bot database"
  test: false
  options:
    - name: "role"
      description: "The role that can interact with every command of the bot, except the most delicate ones (settings commands)"
      required: false
      type: 8

set-remove_ticket_category:
  name: "remove-category"
  description: "Remove a ticket category from the server"
  test: false
  options:
    - name: "category_id"
      description: "The id of the category to be removed"
      required: true
      type: 4
      autocomplete: true

set-ticket_category:
  name: "default-category"
  description: "Choose the default ticket category among the ones already added"
  test: false
  options:
    - name: "category_id"
      description: "The id of the category you want to use as default for the server"
      required: true
      type: 4
      autocomplete: true

set-ticket_panel:
  name: "panel"
  description: "Customize the ticket panel"
  test: false

set-vip_role:
  name: "vip"
  description: "Setup the vip role in the bot database"
  test: false
  options:
    - name: "role"
      description: "The role that will be used as the VIP role"
      required: false
      type: 8

set-vip_ticket_emoji:
  name: "vip-emoji"
  description: "Set the emoji that will be displayed next to the category emoji in vip tickets name"
  test: false
  options:
    - name: "emoji"
      description: "The emoji to be used as the vip ticket emoji"
      required: true
      type: 3


setup:
  description: "Add server to the bot database"
  test: false



# TICKETING

tck-add:
  name: "add"
  description: "Add a user to the ticket"
  test: true
  options:
    - name: "user"
      description: "The user to add"
      required: true
      type: 6
    - name: "ticket-channel"
      description: "The ticket where to add the member to"
      required: false
      type: 7

tck-assign:
  name: "assign"
  description: "Assign a ticket to a category helper"
  test: true
  options:
    - name: "user"
      description: "The user to assign"
      required: true
      type: 6
    - name: "ticket-channel"
      description: "The ticket to assign"
      required: false
      type: 7

tck-claim:
  name: "claim"
  description: "Claim a ticket as helper"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to claim"
      required: false
      type: 7

tck-close:
  name: "close"
  description: "Close a ticket"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to be closed"
      required: false
      type: 7

tck-delete:
  name: "delete"
  description: "Delete a ticket"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to be deleted"
      required: false
      type: 7

tck-open:
  name: "open"
  test: false
  description: "Open a new ticket for a user."
  options:
    - name: "category_id"
      description: "The category in which the ticket will be opened"
      required: true
      type: 4
      autocomplete: true
    - name: "user"
      description: "The user whom to open the ticket to"
      required: true
      type: 9

tck-panel:
  name: "panel"
  description: "Display the ticket panel"
  test: true

tck-remove:
  name: "remove"
  description: "Remove a user from the ticket"
  test: true
  options:
    - name: "member"
      description: "The member to remove"
      required: true
      type: 6
    - name: "ticket-channel"
      description: "The ticket from where to remove the member"
      required: false
      type: 7

tck-reopen:
  name: "reopen"
  description: "Reopen a closed ticket"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to be closed"
      required: false
      type: 7

tck-unassign:
  name: "unassign"
  description: "Unassign a ticket"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to unassign"
      required: false
      type: 7

tck-unclaim:
  name: "unclaim"
  description: "Unclaim a ticket you are assigned to"
  test: true
  options:
    - name: "ticket-channel"
      description: "The ticket to unclaim"
      required: false
      type: 7

tck-unmute:
  name: "unmute"
  description: "Unmuted a previously muted user inside the ticket"
  test: true
  options:
    - name: "user"
      description: "The user to unmute"
      required: true
      type: 6
    - name: "ticket-channel"
      description: "The ticket where to unmute the user"
      required: false
      type: 7

tck-mute:
  name: "mute"
  description: "Mute a user inside the ticket"
  test: true
  options:
    - name: "user"
      description: "The user to mute"
      required: true
      type: 6
    - name: "ticket-channel"
      description: "The ticket where to mute the user"
      required: false
      type: 7